import React from 'react';
import {
  View, Text, StyleSheet, Image, TouchableOpacity,
  StatusBar, ScrollView, Share, Alert,
} from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';

type Params = {
  imageUrl: string;
  amount: number;
  studentName?: string;
  teacherName?: string;
  batchName?: string;
  paidAt?: string;
  upiReference?: string;
};

const PaymentSlipScreen = () => {
  const nav = useNavigation<any>();
  const route = useRoute<any>();
  const {
    imageUrl, amount, studentName, teacherName,
    batchName, paidAt, upiReference,
  } = route.params as Params;

  const handleShare = async () => {
    try {
      await Share.share({
        message: `Payment of ₹${amount.toLocaleString('en-IN')} by ${studentName ?? 'Student'}${batchName ? ` for ${batchName}` : ''}${paidAt ? ` on ${new Date(paidAt).toLocaleDateString('en-IN')}` : ''}.${upiReference ? `\nUPI Ref: ${upiReference}` : ''}`,
        url: imageUrl,
        title: 'RankEdge Payment Slip',
      });
    } catch (e: any) {
      Alert.alert('Share failed', e.message);
    }
  };

  return (
    <View style={s.root}>
      <StatusBar barStyle="light-content" backgroundColor="#0F172A" />
      <View style={s.header}>
        <TouchableOpacity onPress={() => nav.goBack()}>
          <Text style={s.back}>← Back</Text>
        </TouchableOpacity>
        <Text style={s.heading}>Payment Slip</Text>
        <TouchableOpacity onPress={handleShare}>
          <Text style={s.share}>Share</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
        {/* Slip Card */}
        <View style={s.slipCard}>
          {/* Header */}
          <View style={s.slipHeader}>
            <View style={s.logoBox}>
              <Text style={s.logoText}>RE</Text>
            </View>
            <View>
              <Text style={s.slipTitle}>RankEdge</Text>
              <Text style={s.slipSubtitle}>Payment Receipt</Text>
            </View>
            <View style={s.paidStamp}>
              <Text style={s.paidStampText}>PAID</Text>
            </View>
          </View>

          <View style={s.divider} />

          {/* Details */}
          <View style={s.detailsGrid}>
            <SlipRow label="Amount" value={`₹${amount.toLocaleString('en-IN')}`} highlight />
            {studentName && <SlipRow label="Student" value={studentName} />}
            {teacherName && <SlipRow label="Teacher" value={teacherName} />}
            {batchName && <SlipRow label="Batch" value={batchName} />}
            {paidAt && <SlipRow label="Date" value={new Date(paidAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })} />}
            {upiReference && <SlipRow label="UPI Ref" value={upiReference} />}
          </View>

          <View style={s.divider} />

          {/* Screenshot from student */}
          <Text style={s.screenshotLabel}>Payment Screenshot</Text>
          <Image
            source={{ uri: imageUrl }}
            style={s.slipImage}
            resizeMode="contain"
          />

          <View style={s.footerNote}>
            <Text style={s.footerNoteText}>This receipt is generated by RankEdge. Keep it for your records.</Text>
          </View>
        </View>

        <TouchableOpacity style={s.shareBtn} onPress={handleShare}>
          <Text style={s.shareBtnText}>📤 Share Receipt</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

const SlipRow = ({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) => (
  <View style={sr.row}>
    <Text style={sr.label}>{label}</Text>
    <Text style={[sr.value, highlight && sr.valueHighlight]}>{value}</Text>
  </View>
);

const sr = StyleSheet.create({
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8 },
  label: { fontSize: 13, color: '#64748B', fontWeight: '600' },
  value: { fontSize: 14, color: '#F1F5F9', fontWeight: '700', maxWidth: '60%', textAlign: 'right' },
  valueHighlight: { fontSize: 20, color: '#10B981', fontWeight: '900' },
});

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0F172A' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingTop: 56, paddingBottom: 16,
  },
  back: { color: '#6366F1', fontSize: 16, fontWeight: '600' },
  heading: { fontSize: 18, fontWeight: '800', color: '#F8FAFC' },
  share: { color: '#3B82F6', fontSize: 15, fontWeight: '700' },
  content: { padding: 20, paddingBottom: 60 },
  slipCard: {
    backgroundColor: '#1E293B', borderRadius: 20, padding: 20,
    borderWidth: 1, borderColor: '#334155', marginBottom: 20,
  },
  slipHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  logoBox: {
    width: 44, height: 44, borderRadius: 12, backgroundColor: '#312E81',
    alignItems: 'center', justifyContent: 'center',
  },
  logoText: { color: '#A5B4FC', fontWeight: '900', fontSize: 16 },
  slipTitle: { fontSize: 16, fontWeight: '800', color: '#F1F5F9' },
  slipSubtitle: { fontSize: 12, color: '#64748B' },
  paidStamp: {
    marginLeft: 'auto',
    backgroundColor: '#064E3B', borderRadius: 8, paddingHorizontal: 10,
    paddingVertical: 5, borderWidth: 2, borderColor: '#10B981',
  },
  paidStampText: { color: '#10B981', fontWeight: '900', fontSize: 13, letterSpacing: 1 },
  divider: { height: 1, backgroundColor: '#334155', marginVertical: 14 },
  detailsGrid: { gap: 2 },
  screenshotLabel: { fontSize: 13, fontWeight: '700', color: '#64748B', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.8 },
  slipImage: { width: '100%', height: 300, borderRadius: 12, backgroundColor: '#0F172A', marginBottom: 16 },
  footerNote: { alignItems: 'center', paddingTop: 8 },
  footerNoteText: { fontSize: 11, color: '#475569', textAlign: 'center' },
  shareBtn: {
    backgroundColor: '#1E293B', borderRadius: 16, paddingVertical: 16,
    alignItems: 'center', borderWidth: 1, borderColor: '#3B82F6',
  },
  shareBtnText: { color: '#60A5FA', fontWeight: '800', fontSize: 15 },
});

export default PaymentSlipScreen;
