export const PIN_LENGTH = 5;
export const SESSION_EXPIRY_DAYS = 30;
export const MAX_LOGIN_ATTEMPTS = 3;
export const LOCKOUT_MINUTES = 5;
export const OTP_EXPIRY_MINUTES = 15;
export const JOIN_CODE_LENGTH = 8;
export const TIMER_WARNING_SECONDS = 300;
export const AUTO_ATTENDANCE_WINDOW_MINUTES = 10;
export const PAGE_SIZE = 20;
export const MAX_FILE_SIZE_MB = 50;
export const VIDEO_SPEED_OPTIONS = [0.75, 1, 1.25, 1.5, 1.75, 2] as const;

export const ROUTES = {
  SPLASH: 'Splash',
  LANDING: 'Landing',
  LOGIN: 'Login',
  SIGN_UP_TEACHER: 'SignUpTeacher',
  SIGN_UP_STUDENT: 'SignUpStudent',
  SET_PIN: 'SetPin',
  FORGOT_PIN_EMAIL: 'ForgotPinEmail',
  FORGOT_PIN_OTP: 'ForgotPinOtp',
  FORGOT_PIN_NEW: 'ForgotPinNew',
  TEACHER_ROOT: 'TeacherRoot',
  TEACHER_HOME: 'TeacherHome',
  TEACHER_BATCHES: 'TeacherBatches',
  BATCH_DETAIL: 'BatchDetail',
  ADD_EDIT_BATCH: 'AddEditBatch',
  STUDENT_PROFILE_TEACHER: 'StudentProfileTeacher',
  TEACHER_EXAMS: 'TeacherExams',
  CREATE_EDIT_EXAM: 'CreateEditExam',
  QUESTION_CREATOR: 'QuestionCreator',
  QUESTION_BANK: 'QuestionBank',
  EXAM_RESULTS_OVERVIEW: 'ExamResultsOverview',
  STUDENT_EXAM_RESULT: 'StudentExamResult',
  TEACHER_ASSIGNMENTS: 'TeacherAssignments',
  CREATE_EDIT_ASSIGNMENT: 'CreateEditAssignment',
  ASSIGNMENT_SUBMISSIONS: 'AssignmentSubmissions',
  TEACHER_NOTES: 'TeacherNotes',
  UPLOAD_NOTE: 'UploadNote',
  TEACHER_LECTURES: 'TeacherLectures',
  UPLOAD_EDIT_LECTURE: 'UploadEditLecture',
  TEACHER_LIVE_CLASSES: 'TeacherLiveClasses',
  SCHEDULE_LIVE_CLASS: 'ScheduleLiveClass',
  TEACHER_DOUBTS: 'TeacherDoubts',
  DOUBT_THREAD: 'DoubtThread',
  ATTENDANCE_MARK: 'AttendanceMark',
  ATTENDANCE_REPORT: 'AttendanceReport',
  INTERVIEW_UPLOAD: 'InterviewUpload',
  INTERVIEW_PACK_MANAGEMENT: 'InterviewPackManagement',
  TEACHER_ANALYTICS: 'TeacherAnalytics',
  STUDENT_ANALYTICS_DETAIL: 'StudentAnalyticsDetail',
  TEACHER_PAYMENTS: 'TeacherPayments',
  STUDENT_FEE_DETAIL: 'StudentFeeDetail',
  TEACHER_CALENDAR: 'TeacherCalendar',
  TEACHER_TODO: 'TeacherTodo',
  TEACHER_PROFILE: 'TeacherProfile',
  STUDENT_ROOT: 'StudentRoot',
  STUDENT_HOME: 'StudentHome',
  MY_TEACHERS: 'MyTeachers',
  JOIN_BATCH: 'JoinBatch',
  TEACHER_SPACE: 'TeacherSpace',
  STUDENT_EXAMS: 'StudentExams',
  TAKE_EXAM: 'TakeExam',
  EXAM_RESULT: 'ExamResult',
  STUDENT_ASSIGNMENTS: 'StudentAssignments',
  SUBMIT_ASSIGNMENT: 'SubmitAssignment',
  VIEW_GRADED_ASSIGNMENT: 'ViewGradedAssignment',
  NOTES_BROWSER: 'NotesBrowser',
  NOTE_VIEWER: 'NoteViewer',
  STUDENT_LECTURES: 'StudentLectures',
  VIDEO_PLAYER: 'VideoPlayer',
  STUDENT_LIVE_CLASSES: 'StudentLiveClasses',
  STUDENT_DOUBTS: 'StudentDoubts',
  POST_DOUBT: 'PostDoubt',
  MY_ATTENDANCE: 'MyAttendance',
  INTERVIEW_PACKS: 'InterviewPacks',
  INTERVIEW_PRACTICE: 'InterviewPractice',
  INTERVIEW_TRACKER: 'InterviewTracker',
  STUDENT_CALENDAR: 'StudentCalendar',
  STUDENT_TODO: 'StudentTodo',
  FEE_PAYMENT: 'FeePayment',
  PAYMENT_HISTORY: 'PaymentHistory',
  PAYMENT_SLIP: 'PaymentSlip',
  STUDENT_PROFILE: 'StudentProfile',
  UPI_SETUP: 'UpiSetup',
  TEACHER_PAYMENT_NOTIF: 'TeacherPaymentNotif',
} as const;
